In [1]:
import numpy as np

（1）ndarray对象的索引和切片与原生Python中的索引和切片相同，索引是指获取数组中某个特定位置的一个元素；切片是指获取数组中元素的子集（部分数组）。  
（2）ndarray对象的索引和切片序号体系也包括从**0开始的正向递增序号**和**从-1开始的反向递减序号**。

# 1. 一维数组的索引和切片

一维数组的索引和切片与原生python的列表完全相同。

## 1.1 一维数组的索引

In [2]:
a = np.arange(21, 31)
a

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [3]:
# 分别取出索引为0,3，-1，-3的值
a[0],a[3],a[-1],a[-3]

(np.int64(21), np.int64(24), np.int64(30), np.int64(28))

## 1.2 一维数组的切片

In [4]:
a = np.arange(21, 31)
a

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [6]:
# 从索引为1取到索引为8，从索引为-8取到索引为-1
a[1:8],a[-8:-1]

(array([22, 23, 24, 25, 26, 27, 28]), array([23, 24, 25, 26, 27, 28, 29]))

In [ ]:
# 整个列表，反转列表


In [ ]:
# 从开始到索引2，从索引3到最后


In [ ]:
# 在索引1到8范围内每隔一个取一个，整个每隔一个取一个


# 2. 多维数组的索引和切片

多维数组请注意：其维度应该从外层，往里层看，即最外层为第一维度。

## 2.1 多维数组的索引

In [ ]:
a = np.arange(30).reshape(2, 3, 5)
a

In [ ]:
# 取出元素7


In [ ]:
# 正向反向取出元素28


## 2.2 多维数组的切片

In [ ]:
a = np.arange(30).reshape(2, 3, 5)
a

In [ ]:
# 切出数组array([20, 21])


In [ ]:
# 切出数组array([[11, 12, 13],[26, 27, 28]])


In [ ]:
# 切出数组array([[[ 0,  2,  4],[ 5,  7,  9],[10, 12, 14]],[[15, 17, 19],[20, 22, 24],[25, 27, 29]]])


# 3. 练习

## 3.1 练习题目

In [ ]:
temp = np.arange(30).reshape(2,5,3)
temp

第1题：temp[1], temp[1,2], temp[1, 2, 2]依次是多少。  
第2题：temp[:,1,-3], temp[:,1:3,:]依次是多少。  
第3题：分别使用正向递增序号和反向递减序号两种方式从数组temp中索引出元素17。  
第4题：分别使用正向递增序号和反向递减序号两种方式从数组temp中切片出数组  
array([[[9,  10],        [12, 13]],
      [[24, 25],        [27, 28]]])

# 4. 总结

（1）ndarray对象的索引和切片与原生Python中的索引和切片相同，索引是指获取数组中某个特定位置的元素；切片是指获取数组中元素的子集。  
（2）ndarray对象的索引和切片序号体系也包括从0开始的正向递增序号和从-1开始的反向递减序号。  
（3）一维ndarray对象的索引和切片与原生Python中的索引和切片几乎完全一样。  
（4）多维ndarray对象的索引和切片维度应从最外层开始向里层看